version: "3"

services:

  gateway:
    build:
      context: ../
      dockerfile: docker/dockerfile-gateway
    container_name: gateway
    environment:
      server.port: "8080"
      spring.zipkin.base-url: "http://zipkin:9411"
      zuul.routes.front.url: "http://front:8081"
      zuul.routes.back.url: "http://back:8082"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - zipkin
      - front
      - back
    links:
      - zipkin
      - front
      - back
      
  front:
    build:
      context: ../
      dockerfile: docker/dockerfile-front
    container_name: front
    environment:
      server.port: "8081"
      spring.zipkin.base-url: "http://zipkin:9411"
      back.url: "http://back:8082"
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - zipkin
      - back
    links:
      - zipkin
      - back
      
  back:
    build:
      context: ../
      dockerfile: docker/dockerfile-back
    container_name: back
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/mysql?useSSL=false&statementInterceptors=brave.mysql.TracingStatementInterceptor"
      spring.datasource.password: "123456"
      server.port: "8082"
      spring.zipkin.base-url: "http://zipkin:9411"
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - zipkin
      - mysql
    links:
      - zipkin
      - mysql

  zipkin:
    build:
      context: ../
      dockerfile: docker/dockerfile-zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9411/zipkin/"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:5.7.25
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
